name: A Test Action
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.TEST }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - id: step1
        run: node workflow_test.js
      - run: echo ${{needs.job1.outputs.output1}}
      - run: echo ${{env.TEST}}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}}